name: FarmCrops
version: ${plugin.version}
main: player.farmcrops.FarmCrops
api-version: 1.20
author: YourName
description: Advanced farming plugin with holograms, auto-sell, and quests (${plugin.edition} Edition)
depend: [FancyHolograms]
softdepend: [Vault]

commands:
  sellcrops:
    description: Open the crop selling GUI
    usage: /sellcrops
    permission: farmcrops.sell
    aliases: [sell]
    
  farmstats:
    description: View your farming statistics
    usage: /farmstats [player]
    permission: farmcrops.stats
    aliases: [stats]
    
  farmtop:
    description: View the top farmers leaderboard
    usage: /farmtop
    permission: farmcrops.top
    aliases: [top]
    
  farmsettings:
    description: Open the settings GUI
    usage: /farmsettings
    permission: farmcrops.settings
    aliases: [settings]
    
  farmreload:
    description: Reload the plugin configuration
    usage: /farmreload
    permission: farmcrops.reload
    aliases: [reload]
    
  farm:
    description: Open the main farm menu
    usage: /farm
    permission: farmcrops.menu
    aliases: [farmmenu]

permissions:
  farmcrops.*:
    description: Gives access to all FarmCrops features
    children:
      farmcrops.admin: true
      farmcrops.autosell: true
      farmcrops.preview: true
      farmcrops.quest: true
      
  farmcrops.admin:
    description: Admin commands like reload
    default: op
    
  farmcrops.autosell:
    description: Allows using auto-sell feature
    default: false  # NOT default - players need this permission explicitly
    
  farmcrops.preview:
    description: See crop growth previews on right-click
    default: true  # Everyone can see previews
    
  farmcrops.quest:
    description: Access quest system
    default: true
