name: FarmCrops
version: '0.4.0'
description: Weight-based crop economy system with tier progression
main: player.farmcrops.FarmCrops
api-version: '1.21'
author: Player
depend:
  - Vault
softdepend:
  - DecentHolograms
  - PlaceholderAPI

commands:
  sellcrops:
    description: Opens sell GUI to sell custom crops
    usage: /<command>
    aliases: [fcs, sps, sellproduce]
    permission: farmcrops.sell
    permission-message: You don't have permission to sell crops.
