name: FarmCrops
version: ${plugin.version}
main: player.farmcrops.FarmCrops
api-version: 1.20
author: YourName
description: Advanced farming plugin with holograms, auto-sell, and quests (${plugin.edition} Edition)
depend: [FancyHolograms]
softdepend: [Vault]

commands:
  farmcrops:
    description: Main FarmCrops command
    usage: /farmcrops <reload|autosell|quest>
    aliases: [fc, crops]
    
  autosell:
    description: Toggle auto-sell for crops
    usage: /autosell
    permission: farmcrops.autosell
    
  quest:
    description: Open quest menu
    usage: /quest
    permission: farmcrops.quest

permissions:
  farmcrops.*:
    description: Gives access to all FarmCrops features
    children:
      farmcrops.admin: true
      farmcrops.autosell: true
      farmcrops.preview: true
      farmcrops.quest: true
      
  farmcrops.admin:
    description: Admin commands like reload
    default: op
    
  farmcrops.autosell:
    description: Allows using auto-sell feature
    default: false  # NOT default - players need this permission explicitly
    
  farmcrops.preview:
    description: See crop growth previews on right-click
    default: true  # Everyone can see previews
    
  farmcrops.quest:
    description: Access quest system
    default: true
